In [1]:
import polars as pl

DATA         =   "2024_A_S.txt"
TABLE        =   "Jawe2024.csv"
THRESHOLD    =   0.30
WEEKTYPE     =   "w"

print("Polars", pl.__version__, "| Threads:", pl.thread_pool_size())

Polars 1.44.2 | Threads: 32

In [2]:
raw = pl.scan_csv(DATA, separator=";", infer_schema_length=0)

print(raw.collect_schema().len(), "Spalten")
raw.head().collect()

57 Spalten

shape: (5, 57)
┌──────┬──────┬──────┬─────────┬───┬────────┬──────────┬────────┬──────────┐
│ TKNR ┆ Zst  ┆ Land ┆ Strklas ┆ … ┆ Sat_R2 ┆ K_Sat_R2 ┆ Son_R2 ┆ K_Son_R2 │
│ ---  ┆ ---  ┆ ---  ┆ ---     ┆   ┆ ---    ┆ ---      ┆ ---    ┆ ---      │
│ str  ┆ str  ┆ str  ┆ str     ┆   ┆ str    ┆ str      ┆ str    ┆ str      │
╞══════╪══════╪══════╪═════════╪═══╪════════╪══════════╪════════╪══════════╡
│ 7016 ┆ 8001 ┆ 08   ┆ A       ┆ … ┆    -1  ┆ x        ┆    -1  ┆ x        │
│ 7016 ┆ 8001 ┆ 08   ┆ A       ┆ … ┆    -1  ┆ x        ┆    -1  ┆ x        │
│ 7016 ┆ 8001 ┆ 08   ┆ A       ┆ … ┆    -1  ┆ x        ┆    -1  ┆ x        │
│ 7016 ┆ 8001 ┆ 08   ┆ A       ┆ … ┆    -1  ┆ x        ┆    -1  ┆ x        │
│ 7016 ┆ 8001 ┆ 08   ┆ A       ┆ … ┆    -1  ┆ x        ┆    -1  ┆ x        │
└──────┴──────┴──────┴─────────┴───┴────────┴──────────┴────────┴──────────┘

In [3]:
VALUE   =   ["KFZ_R1", "KFZ_R2", "Lkw_R1", "Lkw_R2"]
FLAGS   =   [f"K_{c}" for c in VALUE]

select = raw.select("Zst", "Land", "Datum", "Wotag", "Fahrtzw", "Stunde", *VALUE, *FLAGS)
select.head().collect()

shape: (5, 14)
┌──────┬──────┬────────┬───────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Zst  ┆ Land ┆ Datum  ┆ Wotag ┆ … ┆ K_KFZ_R1 ┆ K_KFZ_R2 ┆ K_Lkw_R1 ┆ K_Lkw_R2 │
│ ---  ┆ ---  ┆ ---    ┆ ---   ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str  ┆ str  ┆ str    ┆ str   ┆   ┆ str      ┆ str      ┆ str      ┆ str      │
╞══════╪══════╪════════╪═══════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 8001 ┆ 08   ┆ 240101 ┆  1    ┆ … ┆ -        ┆ -        ┆ -        ┆ -        │
│ 8001 ┆ 08   ┆ 240101 ┆  1    ┆ … ┆ -        ┆ -        ┆ -        ┆ -        │
│ 8001 ┆ 08   ┆ 240101 ┆  1    ┆ … ┆ -        ┆ -        ┆ -        ┆ -        │
│ 8001 ┆ 08   ┆ 240101 ┆  1    ┆ … ┆ -        ┆ -        ┆ -        ┆ -        │
│ 8001 ┆ 08   ┆ 240101 ┆  1    ┆ … ┆ -        ┆ -        ┆ -        ┆ -        │
└──────┴──────┴────────┴───────┴───┴──────────┴──────────┴──────────┴──────────┘

In [4]:
clean = (
    select
    .with_columns(pl.all().str.strip_chars())
    .with_columns(
        pl.col("Zst").str.zfill(4),
        pl.col("Datum").str.to_date("%y%m%d"),
        pl.col("Stunde").cast(pl.Int8),
        pl.col("Wotag").cast(pl.Int8),
    )
)
clean.head().collect()

shape: (5, 14)
┌──────┬──────┬────────────┬───────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Zst  ┆ Land ┆ Datum      ┆ Wotag ┆ … ┆ K_KFZ_R1 ┆ K_KFZ_R2 ┆ K_Lkw_R1 ┆ K_Lkw_R2 │
│ ---  ┆ ---  ┆ ---        ┆ ---   ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str  ┆ str  ┆ date       ┆ i8    ┆   ┆ str      ┆ str      ┆ str      ┆ str      │
╞══════╪══════╪════════════╪═══════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 8001 ┆ 08   ┆ 2024-01-01 ┆ 1     ┆ … ┆ -        ┆ -        ┆ -        ┆ -        │
│ 8001 ┆ 08   ┆ 2024-01-01 ┆ 1     ┆ … ┆ -        ┆ -        ┆ -        ┆ -        │
│ 8001 ┆ 08   ┆ 2024-01-01 ┆ 1     ┆ … ┆ -        ┆ -        ┆ -        ┆ -        │
│ 8001 ┆ 08   ┆ 2024-01-01 ┆ 1     ┆ … ┆ -        ┆ -        ┆ -        ┆ -        │
│ 8001 ┆ 08   ┆ 2024-01-01 ┆ 1     ┆ … ┆ -        ┆ -        ┆ -        ┆ -        │
└──────┴──────┴────────────┴───────┴───┴──────────┴──────────┴──────────┴──────────┘

In [5]:
clean.group_by("K_KFZ_R1").len().sort("len", descending=True).collect()

shape: (4, 2)
┌──────────┬─────────┐
│ K_KFZ_R1 ┆ len     │
│ ---      ┆ ---     │
│ str      ┆ u32     │
╞══════════╪═════════╡
│ -        ┆ 6190692 │
│ s        ┆ 892766  │
│ u        ┆ 3616    │
│ z        ┆ 1614    │
└──────────┴─────────┘

In [6]:
clean.filter(pl.col("K_KFZ_R1") == "s").head().collect()

shape: (5, 14)
┌──────┬──────┬────────────┬───────┬───┬──────────┬──────────┬──────────┬──────────┐
│ Zst  ┆ Land ┆ Datum      ┆ Wotag ┆ … ┆ K_KFZ_R1 ┆ K_KFZ_R2 ┆ K_Lkw_R1 ┆ K_Lkw_R2 │
│ ---  ┆ ---  ┆ ---        ┆ ---   ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str  ┆ str  ┆ date       ┆ i8    ┆   ┆ str      ┆ str      ┆ str      ┆ str      │
╞══════╪══════╪════════════╪═══════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 8001 ┆ 08   ┆ 2024-01-08 ┆ 1     ┆ … ┆ s        ┆ s        ┆ s        ┆ s        │
│ 8001 ┆ 08   ┆ 2024-02-07 ┆ 3     ┆ … ┆ s        ┆ s        ┆ s        ┆ s        │
│ 8001 ┆ 08   ┆ 2024-02-07 ┆ 3     ┆ … ┆ s        ┆ s        ┆ s        ┆ s        │
│ 8001 ┆ 08   ┆ 2024-02-07 ┆ 3     ┆ … ┆ s        ┆ s        ┆ s        ┆ s        │
│ 8001 ┆ 08   ┆ 2024-02-07 ┆ 3     ┆ … ┆ s        ┆ s        ┆ s        ┆ s        │
└──────┴──────┴────────────┴───────┴───┴──────────┴──────────┴──────────┴──────────┘

In [7]:
join = (
    pl.read_csv(
        TABLE, separator=";", encoding="latin1", infer_schema_length=0,
        columns=["DZ_Nr", "DZ_Name", "Land_Code", "Str_Kl", "Str_Nr", "Koor_UTM32_E", "Koor_UTM32_N"],
    )
    .rename({"DZ_Nr":"Zst"})
    .with_columns(
        pl.col("Koor_UTM32_E", "Koor_UTM32_N").str.replace_all(".","", literal=True).cast(pl.Int64)
    )
)
join.head(10)

shape: (10, 7)
┌──────┬───────────────────┬───────────┬────────┬────────┬──────────────┬──────────────┐
│ Zst  ┆ DZ_Name           ┆ Land_Code ┆ Str_Kl ┆ Str_Nr ┆ Koor_UTM32_E ┆ Koor_UTM32_N │
│ ---  ┆ ---               ┆ ---       ┆ ---    ┆ ---    ┆ ---          ┆ ---          │
│ str  ┆ str               ┆ str       ┆ str    ┆ str    ┆ i64          ┆ i64          │
╞══════╪═══════════════════╪═══════════╪════════╪════════╪══════════════╪══════════════╡
│ 2218 ┆ AD HH-Südost (O)  ┆ HH        ┆ A      ┆ 1      ┆ 572102       ┆ 5929284      │
│ 2217 ┆ AD HH-Südost (W)  ┆ HH        ┆ A      ┆ 1      ┆ 569966       ┆ 5929459      │
│ 5675 ┆ AK Leverkusen (O) ┆ NW        ┆ A      ┆ 1      ┆ 364845       ┆ 5658635      │
│ 5035 ┆ AK Leverkusen (W) ┆ NW        ┆ A      ┆ 1      ┆ 358801       ┆ 5655933      │
│ 0353 ┆ AS Eppelborn      ┆ SL        ┆ A      ┆ 1      ┆ 353633       ┆ 5475577      │
│ 5121 ┆ Ascheberg         ┆ NW        ┆ A      ┆ 1      ┆ 403168       ┆ 5743440      │
│ 1101 ┆ Bad Oldesloe      ┆ SH        ┆ A      ┆ 1      ┆ 594121       ┆ 5961309      │
│ 1108 ┆ Bad Schwartau     ┆ SH        ┆ A      ┆ 1      ┆ 609762       ┆ 5972762      │
│ 1102 ┆ Barsbüttel        ┆ SH        ┆ A      ┆ 1      ┆ 578185       ┆ 5935581      │
│ 0173 ┆ Bierfeld          ┆ SL        ┆ A      ┆ 1      ┆ 352990       ┆ 5496258      │
└──────┴───────────────────┴───────────┴────────┴────────┴──────────────┴──────────────┘

In [8]:
ganglinie = (
    join
    .filter(pl.col("Fahrtzw") == WEEKTYPE)
    .with_columns(
        (pl.col("KFZ_R1") + pl.col("KFZ_R2")).alias("Kfz"),
        (pl.col("Lkw_R1") + pl.col("Lkw_R2")).alias("Lkw"),
    )
    .join(join.lazy(), on="Zst", how="inner")
    .sort("Zst","Stunde")
    .collect()
)
print(Ganglinie.height, "Zeilen =", Ganglinie["Zst"].n_unique(), "Zählstellen x 24 Studnen")
ganglinie.head(8)

ColumnNotFoundError: unable to find column "Fahrtzw"; valid columns: ["Zst", "DZ_Name", "Land_Code", "Str_Kl", "Str_Nr", "Koor_UTM32_E", "Koor_UTM32_N"]

In [ ]:
print(raw.collect_schema().names())
print(clean.collect_schema().names())
print(join.collect_schema().names())
print(ganglinie.collect_schema().names())